ludus:
  - vm_name: "{{ range_id }}-kali"
    hostname: "kali"
    template: kali-x64-desktop-template
    vlan: 10
    ip_last_octet: 20
    ram_gb: 4
    cpus: 4
    linux: true
    testing:
      snapshot: false
      block_internet: false
  - vm_name: "{{ range_id }}-dc1"
    hostname: "dc1"
    template: win2019-server-x64-template
    vlan: 10
    ip_last_octet: 10
    ram_gb: 4
    cpus: 2
    windows:
      sysprep: true
    domain:
      fqdn: domain.local
      role: primary-dc
  - vm_name: "{{ range_id }}-mssql1"
    hostname: "mssql1"
    template: win2019-server-x64-template
    vlan: 10
    ip_last_octet: 11
    ram_gb: 4
    cpus: 2
    windows:
      sysprep: true
    roles:
      - badsectorlabs.ludus_mssql
    domain:
      fqdn: domain.local
      role: member
  - vm_name: "{{ range_id }}-mssql2"
    hostname: "mssql2"
    template: win2019-server-x64-template
    vlan: 10
    ip_last_octet: 12
    ram_gb: 4
    cpus: 2
    windows:
      sysprep: true
    roles:
      - badsectorlabs.ludus_mssql
    domain:
      fqdn: domain.local
      role: member
